# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 19:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='order',
        ),
        migrations.RemoveField(
            model_name='list',
            name='description',
        ),
        migrations.RemoveField(
            model_name='list',
            name='listId',
        ),
        migrations.AddField(
            model_name='card',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='card',
            name='listId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='board.List'),
        ),
        migrations.AddField(
            model_name='list',
            name='order',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
