# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20170916_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='order',
            field=models.IntegerField(),
        ),
    ]
