# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 03:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20170916_1949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='listId',
            new_name='ls',
        ),
    ]
